# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

dict = {0:1, 1:1}

def fib(x):

    if x in dict:
        return dict[x]
    recursion = fib(x-1) + fib(x-2)
    dict[x] = recursion
    return recursion

def fib_even(x):
    sum = 0
    i = 1
    while fib(i) < x:
        if fib(i) % 2 == 0:
            sum += dict[i]
        i += 1
    return sum

fib_even(4000000)